import { Dimensions, StyleSheet } from "react-native"
import { moderateScale, scale, verticalScale } from "../../utils/scaling"

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window")
const isMobile = SCREEN_WIDTH < 500

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: isMobile ? moderateScale(12) : moderateScale(20),
    
  },
  videoContainer: {
    width: isMobile? "100%": "70%",
    justifyContent: "space-between",
    alignItems: "center",
     // Column for mobile, row for tablet
  },
  videoView: {
    borderRadius: isMobile? moderateScale(10): moderateScale(5),
    justifyContent: "center",
    alignItems: "center",
    marginVertical: isMobile ? verticalScale(10) : verticalScale(10),
    width: "100%", // Full width for mobile, half for tablet
    position: "relative",
    maxWidth: SCREEN_WIDTH * 0.95,
    maxHeight: isMobile ? SCREEN_HEIGHT * 0.8 : SCREEN_HEIGHT * 0.5, // Slightly larger for tablet
  },
  aspectRatio16_12: {
    aspectRatio: isMobile ? 16 / 12 : 16 / 9, // Taller aspect ratio for mobile
    zIndex: 2,
  },
  text: {
    fontWeight: "400",
    textAlign: "center",
    lineHeight: isMobile ? moderateScale(45) : moderateScale(50),
    paddingHorizontal: isMobile ? scale(20) : scale(30),
    fontSize: isMobile ? moderateScale(16) : moderateScale(20), // Larger text for tablet
  },
  controlsContainer: {
    position: "absolute",
    top: moderateScale(10),
    right: moderateScale(10),
    alignItems: "flex-end",
    zIndex: 10,
  },
  toggleButton: {
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: moderateScale(20),
    padding: isMobile ? moderateScale(8) : moderateScale(5),
  },
  settingsControls: {
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: moderateScale(10),
    padding: isMobile ? moderateScale(10) : moderateScale(12),
    alignItems: "center",
    gap: isMobile ? moderateScale(8) : moderateScale(5),
    zIndex: 11,
    marginTop: moderateScale(5),
  },
  settingsButton: {
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: moderateScale(20),
    padding: isMobile ? moderateScale(8) : moderateScale(5),
    width: isMobile ? moderateScale(40) : moderateScale(38),
    height: isMobile ? moderateScale(40) : moderateScale(38),
    justifyContent: "center",
    alignItems: "center",
  },
  fontControls: {
    alignItems: "center",
    gap: isMobile ? moderateScale(8) : moderateScale(10),
    marginTop: isMobile ? moderateScale(8) : moderateScale(10),
    zIndex: 12,
  },
  fontButton: {
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: moderateScale(20),
    padding: isMobile ? moderateScale(8) : moderateScale(10),
    width: isMobile ? moderateScale(40) : moderateScale(48),
    height: isMobile ? moderateScale(40) : moderateScale(48),
    justifyContent: "center",
    alignItems: "center",
  },
  fontButtonText: {
    fontSize: isMobile ? moderateScale(16) : moderateScale(18),
    fontWeight: "600",
    textAlign: "center",
  },
  speedButtonText: {
    fontSize: isMobile ? moderateScale(16) : moderateScale(18),
    fontWeight: "600",
    textAlign: "center",
  },
  buttonContainer: {
    position: "absolute",
    bottom: isMobile ? verticalScale(-20) : verticalScale(-25),
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: isMobile ? scale(20) : scale(25),
    zIndex: 5,
    width: "100%",
    paddingHorizontal: isMobile ? scale(20) : scale(30),
  },
cameraButton: {
    backgroundColor: "#fff",
    borderRadius: moderateScale(25),
    padding: isMobile ? moderateScale(10) : moderateScale(12),
    justifyContent: "center", // Center vertically
    alignItems: "center", // Center horizontally
    width: isMobile ? moderateScale(60) : moderateScale(70), // Explicit width for circular shape
    height: isMobile ? moderateScale(60) : moderateScale(70), // Explicit height for circular shape
  },
  restartButton: {
    backgroundColor: "#fff",
    borderRadius: moderateScale(25),
    padding: isMobile ? moderateScale(10) : moderateScale(12),
    justifyContent: "center", // Center vertically
    alignItems: "center", // Center horizontally
    width: isMobile ? moderateScale(60) : moderateScale(70), // Explicit width for circular shape
    height: isMobile ? moderateScale(60) : moderateScale(70), // Explicit height for circular shape
  },
  buttonText: {
    fontSize: moderateScale(12),
    textAlign: "center", // Ensure text is centered
    color: "black",
    // Remove marginTop to prevent offset
  },
  scrollView: {
    width: "100%",
    height: "100%",
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: isMobile ? verticalScale(20) : verticalScale(30),
  },
  countdownContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0)",
    zIndex: 15,
    borderRadius: moderateScale(50),
  },
  countdownText: {
    fontSize: isMobile ? moderateScale(60) : moderateScale(70),
    fontWeight: "bold",
    textAlign: "center",
    color: "red",
  },
  pasteSuccessContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -100 }, { translateY: -25 }],
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(8),
    borderRadius: moderateScale(8),
    zIndex: 1000,
  },
  pasteSuccessText: {
    marginLeft: moderateScale(8),
    fontSize: moderateScale(14),
    fontWeight: '500',
    color: 'white',
  },
  bottomControls: {
    position: 'absolute',
    bottom: moderateScale(30),
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(40),
    zIndex: 100,
  },
  recordButton: {
    width: moderateScale(80),
    height: moderateScale(80),
    borderRadius: moderateScale(40),
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: moderateScale(20),
    borderWidth: 4,
    borderColor: 'white',
  },
  recordButtonInner: {
    width: moderateScale(50),
    height: moderateScale(50),
    borderRadius: moderateScale(25),
  },
  contentContainer: {
    flex: 1,
    padding: isMobile ? moderateScale(10) : moderateScale(12),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000",
    paddingHorizontal: isMobile ? scale(50) : scale(60),
  },
  lottie: {
    width: isMobile ? moderateScale(100) : moderateScale(120),
    height: isMobile ? moderateScale(100) : moderateScale(120),
    backgroundColor: "#000",
  },
  // Full Screen Styles
  fullScreenContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  camera: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  permissionText: {
    color: 'white',
    fontSize: moderateScale(18),
    textAlign: 'center',
    marginBottom: moderateScale(20),
    paddingHorizontal: moderateScale(20),
  },
  retryButton: {
    backgroundColor: '#259B9A',
    paddingHorizontal: moderateScale(30),
    paddingVertical: moderateScale(12),
    borderRadius: moderateScale(25),
    marginTop: moderateScale(10),
  },
  retryButtonText: {
    color: 'white',
    fontSize: moderateScale(16),
    fontWeight: '600',
    textAlign: 'center',
  },
  topControls: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    position: 'absolute',
    top: moderateScale(50),
    left: moderateScale(20),
    right: moderateScale(20),
    zIndex: 10,
  },
  leftTopControls: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  upArrowButton: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: moderateScale(8),
  },
  closeButton: {
    width: moderateScale(44),
    height: moderateScale(44),
    borderRadius: moderateScale(22),
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraFlipButton: {
    width: moderateScale(44),
    height: moderateScale(44),
    borderRadius: moderateScale(22),
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: moderateScale(20),
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(6),
  },
  recordingDot: {
    width: moderateScale(8),
    height: moderateScale(8),
    borderRadius: moderateScale(4),
    backgroundColor: '#ff0000',
    marginRight: moderateScale(8),
  },
  pausedDot: {
    backgroundColor: '#ffa500',
  },
  timerText: {
    color: 'white',
    fontSize: moderateScale(14),
    fontWeight: '600',
    fontFamily: 'monospace',
  },
  limitText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: moderateScale(12),
    marginLeft: moderateScale(4),
  },
  pauseButton: {
    width: moderateScale(50),
    height: moderateScale(50),
    borderRadius: moderateScale(25),
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: moderateScale(15),
  },
  teleprompterOverlay: {
    position: 'absolute',
    top: moderateScale(40),
    left: 0,
    right: 0,
    height: moderateScale(300),
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderRadius: 0,
    padding: moderateScale(20),
    paddingTop: moderateScale(40),
    zIndex: 500,
  },
  teleprompterLandscape: {
    position: 'absolute',
    top: moderateScale(50),
    left: moderateScale(50),
    right: moderateScale(75),
    height: moderateScale(300),
    width: SCREEN_WIDTH - moderateScale(100),
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderRadius: moderateScale(10),
    padding: moderateScale(15),
    paddingTop: moderateScale(30),
    zIndex: 500,
    transform: [{ rotate: '0deg' }],
  },
  editIcon: {
    position: 'absolute',
    top: moderateScale(15),
    right: moderateScale(15),
    width: moderateScale(28),
    height: moderateScale(28),
    borderRadius: moderateScale(14),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  rotateIcon: {
    position: 'absolute',
    bottom: moderateScale(15),
    right: moderateScale(15),
    width: moderateScale(28),
    height: moderateScale(28),
    borderRadius: moderateScale(14),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  teleprompterText: {
    color: 'white',
    textAlign: 'left',
    lineHeight: moderateScale(28),
    fontSize: moderateScale(18),
    fontWeight: '400',
  },
  sideButton: {
    width: moderateScale(60),
    height: moderateScale(60),
    borderRadius: moderateScale(30),
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingsPanel: {
    position: 'absolute',
    top: moderateScale(50),
    left: moderateScale(-150),
    width: moderateScale(300),
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    borderRadius: moderateScale(15),
    padding: moderateScale(20),
    zIndex: 1000,
  },
  settingsPanelTitle: {
    color: 'white',
    fontSize: moderateScale(14),
    textAlign: 'center',
    marginBottom: moderateScale(20),
    lineHeight: moderateScale(18),
  },
  settingsRow: {
    marginBottom: moderateScale(20),
  },
  settingsLabel: {
    color: 'white',
    fontSize: moderateScale(16),
    fontWeight: '600',
    marginBottom: moderateScale(10),
  },
  controlButton: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sliderTrack: {
    flex: 1,
    height: moderateScale(6),
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: moderateScale(3),
    marginHorizontal: moderateScale(15),
    position: 'relative',
  },
  sliderProgress: {
    height: '100%',
    backgroundColor: '#4CAF50',
    borderRadius: moderateScale(3),
  },
  sliderThumb: {
    position: 'absolute',
    top: moderateScale(-7),
    width: moderateScale(20),
    height: moderateScale(20),
    borderRadius: moderateScale(10),
    backgroundColor: '#4CAF50',
    marginLeft: moderateScale(-10),
  },
  cameraControlsBelow: {
    position: 'absolute',
    top: moderateScale(350), // Position below teleprompter
    left: -30,
    right: -30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: moderateScale(40),
    zIndex: 600,
  },
  recordingControlsBelow: {
    position: 'absolute',
    bottom: moderateScale(30), // Position at bottom like original bottom controls
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: moderateScale(40),
    zIndex: 700,
  },
})

export default styles